### PR TITLE
Make logs more parseable when in debug mode

### PR DESCRIPTION
**Pull request by SchizoDuckie**
\r for "newlines" has side effects that i had planned to resolve in the previous commit.

### CODE REVIEW

**Review by carlhoerberg — COMMENTED** [review]
Wasnt \r correct but then add a \n at the end?

**Comment by SchizoDuckie** [comment]
I would be satisfied with either of those, as long as log lines can be separated by \n. I have not checked the codebase for what can happen with other control characters yet. Please advise what you would prefer.

**Comment by ameenross** [comment]
`\r` is really only correct for Mac OS (not OS X) and older machines such as Commodore. On linux, a `\r` actually can be used to overwrite the current line of output in a console, it is *not* a newline. I presume it's the same on OS X. It really is no longer valid today.

`\r\n` are DOS/Windows newlines. The rest of the world uses `\n` end of story.

**Comment by ameenross** [comment]
I made an issue about this, #42. I didn't realize there was already a PR... but this PR probably doesn't cover all newlines.

**Comment by carlhoerberg** [comment]
The reason for this is the `10 clients                1 upstreams` status line, it's being overwritten for each log. But i guess we shouldn't dispaly the statusline if STDOUT isn't a TTY, and then use `\n` instead as normal

**Comment by carlhoerberg** [comment]
or skip the status line all together..

**Comment by carlhoerberg** [comment]
Fixed in master and v0.5.0

**Pull request closed without merging**
