### PR TITLE
Build packages for Debian 12, remove EoL systems

### PR DESCRIPTION
**Pull request by dentarg**
Debian 12 was released 2024-02-10:
https://www.debian.org/releases/bookworm/

Ubuntu 18.04 and Debian 10 has reached end of life: https://www.debian.org/releases/buster/
https://endoflife.software/operating-systems/linux/ubuntu

Fixes https://github.com/cloudamqp/amqproxy/issues/149

### CODE REVIEW

**Comment by dentarg** [comment]
I guess we will try this in main.

**Comment by melroy89** [comment]
Thanks! This helped us a lot at mbin.

**Comment by TheVillageGuy** [comment]
> Debian 12 was released 2024-02-10: https://www.debian.org/releases/bookworm/
> 
> Ubuntu 18.04 and Debian 10 has reached end of life: https://www.debian.org/releases/buster/ https://endoflife.software/operating-systems/linux/ubuntu
> 
> Fixes #149

That's 12.5, I've been running 12 for roughly half a year now

**Comment by TheVillageGuy** [comment]
I still can't install amqproxy,

```kbin@debian-8gb-nbg1-1:/var/www/kbin$ curl -s https://packagecloud.io/install/re                                                                                                                                                                                                positories/cloudamqp/amqproxy/script.deb.sh | sudo bash
Detected operating system as debian/bookworm.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.6.1
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/cloudamqp_amqproxy.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/cloudamqp_amqproxy-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
kbin@debian-8gb-nbg1-1:/var/www/kbin$ ^Cano
kbin@debian-8gb-nbg1-1:/var/www/kbin$ locate amqproxy.ini
kbin@debian-8gb-nbg1-1:/var/www/kbin$ sudo apt-get install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
kbin@debian-8gb-nbg1-1:/var/www/kbin$ sudo apt-get install amqproxy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package amqproxy
kbin@debian-8gb-nbg1-1:/var/www/kbin$ sudo apt-get update
Hit:1 http://mirror.hetzner.com/debian/packages bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://security.debian.org/debian-security bookworm-security InRelease
Hit:5 http://mirror.hetzner.com/debian/packages bookworm-updates InRelease
Hit:6 http://mirror.hetzner.com/debian/security bookworm-security InRelease
Hit:7 https://packages.sury.org/php bookworm InRelease
Hit:8 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:9 https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy InRelease
Ign:10 https://packagecloud.io/cloudamqp/amqproxy/debian bookworm InRelease
Get:11 https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy InRelease [2,976 B]
Err:12 https://packagecloud.io/cloudamqp/amqproxy/debian bookworm Release
  404  Not Found [IP: 2600:1f1c:2e5:6901:7d8b:82c3:d880:13b0 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/cloudamqp/amqproxy/debian bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by melroy89** [comment]
It seems that bookworm is still missing here: https://packagecloud.io/app/cloudamqp/amqproxy/search?q=&filter=all&dist=debian%2Fbookworm. Maybe it take some time before a new version/package get released at packagecloud.io?

**Comment by dentarg** [comment]
Packages are only uploaded to package cloud on a release. You can find packages as artifacts at https://github.com/cloudamqp/amqproxy/actions/runs/8173019877

**Pull request merged**
